carlosas/phpat

- README.md
- phpat
- src/App.php
- src/App/Configuration.php
- src/App/Provider.php
- src/Input/ArgvInput.php
- src/Input/InputInterface.php
This PR aims to add the option dry-run as requested in #20. The implementation allows enabling dry-run in 2 ways:
- Adding the option to the configuration file. Works like the verbosity option
- Passing an option to the command. This will parse the arguments passed to the command and see if the option --dry-run was passed.
The implementation of the parser of the arguments is very simple and I'm sure that could be improved.
Also I've not provided tests because I could not think of a way to write a test that fails and check the status code without breaking the test suite. I tested by changing a test to make it fail and running manually the tests and checking the exit code. If you have any suggestion to test this in a more automated way I'd like to know to add it.
> Add option dry-run

- src/Rule/RuleBuilder.php
While debugging I ran into an error where not having a rule type would cause a type error. This PR catches that case and attempts to give a helpful message to the user.
> Throw exception if rule type not declared

- README.md
Thanks for the awesome tool! 🚀 
I have some notes with regards to the semantic versioning and release process note in the readme.
[SemVer 2.0 rule 4.](https://semver.org/#spec-item-4) says:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
Also, [rule 7.](https://semver.org/#spec-item-7) says:
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is …
> Update note on semantic versioning and BC

- src/App/Provider.php
Although Symfony used `yml` before, the `yaml` extension should be preferred.
Do you want me to update the README as well?
> Support both `yml` and `yaml` extension

- doc/SELECTORS.md
- src/Selector/ComposerDependencySelector.php
- src/Selector/ComposerFileParser.php
- src/Selector/ComposerSourceSelector.php
- src/Selector/Selector.php
- tests/architecture/ComposerTest.php
- tests/unit/Selector/ComposerDependencySelectorTest.php
- tests/unit/Selector/ComposerFileParserTest.php
- tests/unit/Selector/ComposerSourceSelectorTest.php
- tests/unit/Selector/Mock/composer.json
- tests/unit/Selector/Mock/composer.lock
This adds 2 more selectors:
* One for source files declared in composer.json
* One for dependencies declared in composer.json
The functionality is pretty much a 1:1 copy from phparch with some additional tweaks.
Example usage can be found in `tests/architecture/ComposerTest`  
I am not happy with the naming since `areComposerSource` does not really communicate the intent of the selector very well.
> Add composer selectors

- src/Parser/Ast/PhpDocTypeResolver.php
- tests/functional/architecture/DependencyTest.php
- tests/functional/fixtures/Dependency/DocBlock.php
- tests/functional/fixtures/GenericInner.php
- tests/functional/fixtures/GenericOuter.php
This adds support for tracking both, generic 'outer' types as well as the inner types.
The underlying phpstan library already supported this, so it was quite easy to implement.
> Add support for generic types

- phpcs.xml
There are proper places for these.
1. Composer scripts
2. CI configs
> Clean up args from PHPCS config

- src/Parser/Ast/FullClassName.php
- tests/unit/Rule/Assertion/AbstractAssertionTestCase.php
- tests/unit/Selector/AbstractSelectorTestCase.php
I'm running phpat against a large (+10k classes) codebase.  
I tried profiling it to check for bottleneck that may become obvious with this volume of code.
I stumbled onto `FullClassName` most of the runtime is spent building a FQCN that we already got in the first place.  
You can see the profiling before (45% percent is spent in getFQCN):  
https://blackfire.io/profiles/bb41e06c-67af-49d3-a402-0df26b3971f8/graph  
And after (runtime went from 6m37s to 2m56s):  
https://blackfire.io/profiles/f1a68e74-2f49-401c-b2ff-78a3ce75b080/graph
> Optimize parser FullClassName

- src/File/FileFinder.php
- src/Parser/Ast/MapBuilder.php
- tests/unit/Parser/Ast/MapBuilderTest.php
- tests/unit/Parser/Ast/mocks/IncludedClass.php
- tests/unit/Parser/Ast/mocks/excluded-directory/ExcludedClass.php
resolves #156
I noticed, that `FileFinder::findSrcFiles` has an `$excluded` parameter, that is never specified - but I didn't want to do too many changes in this PR.
> Do not analyze excluded files

- .github/workflows/release-phar.yml
- bin/phpat
- build.php
This pull requests fixes 3 issues:
- The path to the binary was incorrect, so the file in phar project was empty
- As the phpat binary is put at the top level the path to vendor/autload.php was incorrect
- After fixing the above I was still getting autoload errors about missing PHPUnit files
`failed to open stream: phar error: "vendor/phpunit/phpunit/src/Framework/Assert/Functions.php" is not a file in phar "/home/lefty/Workspace/phpat/dist/phpat.phar" in phar:///.../phpat/dist/phpat.phar/vendor/composer/autoload_real.php on line 55`
As those files are not necessary for the library to work and increase the size of the phar archive I instructed workflow not to install dev dependencies
> Fix for issue 182 - broken phar file

- ci/psalm.xml
- doc/SELECTORS.md
- extension.neon
- src/Rule/Assertion/Declaration/ShouldBeReadonly/IsReadonlyRule.php
- src/Rule/Assertion/Declaration/ShouldBeReadonly/ShouldBeReadonly.php
- src/Rule/Extractor/Declaration/ReadonlyExtractor.php
- src/Selector/IsReadonly.php
- src/Selector/SelectorPrimitive.php
- src/Test/Builder/AssertionStep.php
- tests/unit/rules/ShouldBeReadonly/ReadonlyClassTest.php
> Add shouldBeReadonly assertion

- docs/documentation/assertions.md
- extension.neon
- src/Rule/Assertion/Declaration/ShouldHaveOnlyOnePublicMethod/HasOnlyOnePublicMethodRule.php
- src/Rule/Assertion/Declaration/ShouldHaveOnlyOnePublicMethod/ShouldHaveOnlyOnePublicMethod.php
- src/Rule/Extractor/Declaration/OnePublicMethodExtractor.php
- src/Test/Builder/AssertionStep.php
- tests/fixtures/Special/ClassWithOnePublicMethod.php
- tests/unit/rules/ShouldHaveOnlyOnePublicMethod/ClassWithOnlyOnePublicMethodTest.php
- tests/unit/rules/ShouldHaveOnlyOnePublicMethod/GoodImplementationClassWithOnlyOnePublicMethodTest.php
Useful for ensuring that Application Services, Controllers… have only one public method in order to enforce SRP. 🙂
I've tried to follow all the code practices in the repo, feel free to make any changes.
[PHPMD offers this feature as well](https://phpmd.org/rules/codesize.html#ExcessivePublicCount:~:text=TooManyPublicMethods), but imho, it has more sense as an architectural layer.
> feat: add ShouldHaveOnlyOnePublicMethod rule

- src/Test/Attributes/Test.php
- src/Test/TestParser.php
- tests/architecture/ConfigurationTest.php
Hello!
PHPUnit recently added the ability to use [an attribute](https://docs.phpunit.de/en/10.4/attributes.html) to mark test methods instead of requiring the method name to start with `test` or use the `/** @test */` PHPDoc annotation.
I much prefer using this style over the others I mentioned so figured I'd implement it, backwards compatibility is maintained. 
Thanks!
> Add Test attribute

- docs/documentation/assertions.md
- extension.neon
- src/Rule/Assertion/Declaration/ShouldBeInterface/IsInterfaceRule.php
- src/Rule/Assertion/Declaration/ShouldBeInterface/ShouldBeInterface.php
- src/Rule/Extractor/Declaration/InterfaceExtractor.php
- src/Test/Builder/AssertionStep.php
- tests/unit/rules/ShouldBeInterface/InterfaceClassTest.php
- tests/unit/rules/ShouldBeInterface/ShowRuleNameInterfaceClassTest.php
Hey everyone,
I would like to check that all _classes_ in a specific namespace are interfaces. Something like this:
```php
public function testAllClassesInNamespaceNeedToBeInterfaces(): Rule
{
return PHPat::rule()
->classes(
Selector::inNamespace('App\Interfaces'),
Selector::inNamespace('Package\One\Interfaces'),
Selector::inNamespace('Package\Two\Interfaces'),
)
->shouldBeInterface();
}
```
> Add new IsInterfaceRule

- docs/documentation/assertions.md
- extension.neon
- src/Rule/Assertion/Relation/RelationAssertion.php
- src/Rule/Assertion/Relation/ShouldInclude/IncludedTraitsRule.php
- src/Rule/Assertion/Relation/ShouldInclude/ShouldInclude.php
- src/Rule/Assertion/Relation/ShouldNotInclude/IncludedTraitsRule.php
- src/Rule/Assertion/Relation/ShouldNotInclude/ShouldNotInclude.php
- src/Rule/Extractor/Relation/AllTraitsExtractor.php
- src/Selector/ClassIncludes.php
- src/Selector/SelectorPrimitive.php
- src/Test/Builder/AssertionStep.php
- tests/fixtures/Simple/SimpleTraitTwo.php
- tests/unit/rules/ShouldInclude/IncludedTraitsTest.php
- tests/unit/rules/ShouldInclude/ShowRuleNameIncludedTraitsTest.php
- tests/unit/rules/ShouldNotInclude/IncludedTraitsTest.php
- tests/unit/rules/ShouldNotInclude/ShowRuleNameIncludedTraitsTest.php
Fixes https://github.com/carlosas/phpat/issues/263
This PR brings back traits assertions to PhpAt from pre-0.10 PHPStan extension version.
It's my 1st PR here, feel free to point out what's wrong if needed, I'll be happy to fix it.
> Add ShouldInclude and ShouldNotInclude rules

- docs/CHANGELOG.md
- extension.neon
- src/Rule/Assertion/Relation/CanOnlyDepend/CatchBlockRule.php
- src/Rule/Assertion/Relation/ShouldNotDepend/CatchBlockRule.php
- src/Rule/Extractor/Relation/CatchBlockExtractor.php
- tests/fixtures/FixtureClass.php
- tests/unit/rules/CanOnlyDepend/CatchBlockTest.php
- tests/unit/rules/ShouldNotDepend/CatchBlockTest.php
This enables PHPat to detect dependencies to exception classes in catch blocks.
Example: Given a class that isn't allowed to depend on `SomeException`, the following code snippet now correctly reports a violation of this rule.
```php
try {
// something dangerous
} catch(SomeException $e) {
// ...
}
```
> Detect dependencies in catch blocks

- ci/psalm.xml
- docs/documentation/rules.md
- src/Test/RuleValidator.php
- src/Test/RuleValidatorInterface.php
- src/Test/TestExtractor.php
- src/Test/TestExtractorInterface.php
- src/Test/TestParser.php
- tests/integration/test/TestParser/ParsesTestsTest.php
- tests/integration/test/TestParser/TestClass.php
This PR provides the possibility to return an iterable of Rules from the test-Functions, so thay you can create dynamic rulesets.
This PR also adds the internal classes `TestExtractor` to extend a new `TestExtractorInterface` and `RuleValidator` to extend a new `RuleValidatorInterface`, so that the `TestParser` is testable without the actual classes
New feature:
```php
namespace App\Tests\Architecture;
use PHPat\Selector\Selector;
use PHPat\Test\Builder\Rule;
use PHPat\Test\PHPat;
final class ConfigurationTest
{
private const DOMAINS = [
'App\Domain1',
'App\Domain2',
];
/**
* @return iterable<string, Rule>
*/
public function test_domain_independence(): iterable
{
foreach(self::DOMAINS as $domain) {
yield $domain => PHPat::rule()
->classes(Selector::inNamespace($domain)) …
```
> Dynamic ruleset collection

- docs/documentation/selectors.md
- src/Selector/IsNotFinal.php
- src/Selector/IsNotTrait.php
- src/Selector/IsTrait.php
- src/Selector/SelectorPrimitive.php
This patch adds `IsTrait`  and `IsNotTrait` selectors.
> add `IsTrait`  and `IsNotTrait` selectors

- docs/documentation/selectors.md
- src/Selector/IsError.php
- src/Selector/IsException.php
- src/Selector/IsThrowable.php
- src/Selector/SelectorPrimitive.php
This patch adds `IsException`, `IsError`, and `IsThrowable ` selectors.
> add `IsException`, `IsError`, and `IsThrowable` selectors

- docs/documentation/selectors.md
- docs/getting-started.md
Updated removed methods in documentation:
- `Selector::namespace()` to `Selector::inNamespace()`
- `Selector::abstract()` to `Selector::isAbstract()`
> Replace Selector::namespace() and Selector::abstract() in docs

- docs/documentation/selectors.md
- src/Selector/Modifier/AllOfSelectorModifier.php
- src/Selector/Modifier/AnyOfSelectorModifier.php
- src/Selector/Modifier/AtLeastCountOfSelectorModifier.php
- src/Selector/Modifier/AtMostCountOfSelectorModifier.php
- src/Selector/Modifier/NoneOfSelectorModifier.php
- src/Selector/Modifier/OneOfSelectorModifier.php
- src/Selector/Selector.php
rebased version of https://github.com/carlosas/phpat/pull/289
> Rebase selector modifiers
